apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fg6jsn1mu-go 
  janus-idp.io/tekton: fg6jsn1mu-go
  backstage.io/kubernetes-id: fg6jsn1mu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fg6jsn1mu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  