apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fg6jsn1mu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fg6jsn1mu-go 
  name: fg6jsn1mu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fg6jsn1mu-go 
